add_library(bt_objects OBJECT)
target_sources(bt_objects PRIVATE
	ai_heli.cpp
	ai_launcher.cpp
	ai_machinegunner_player.cpp
	ai_mortar.cpp
	ai_shilka.cpp
	ai_tank.cpp
	ai_trooper.cpp
	ballistic_missile.cpp
	barrack.cpp
	barrier.cpp
	boat.cpp
	bomb.cpp
	buggy.cpp
	bullet.cpp
	cannon.cpp
	car.cpp
	civilian.cpp
	corpse.cpp
	cow.cpp
	ctf_base.cpp
	ctf_flag.cpp
	damage.cpp
	destructable_object.cpp
	dirt.cpp
	explosion.cpp
	explosive.cpp
	fakemod.cpp
	gta_car.cpp
	heli.cpp
	helicopter.cpp
	item.cpp
	kamikaze.cpp
	launcher.cpp
	machinegunner_on_launcher.cpp
	mine.cpp
	missile.cpp
	missiles_in_vehicle.cpp
	mortar.cpp
	mortar_bullet.cpp
	old_school_destructable.cpp
	paratrooper.cpp
	pillbox.cpp
	poison.cpp
	raider_heli.cpp
	sandworm.cpp
	shilka.cpp
	shilka_turret.cpp
	single_pose.cpp
	slime.cpp
	submarine.cpp
	tank.cpp
	teleport.cpp
	tooltip.cpp
	traffic_lights.cpp
	train.cpp
	trooper.cpp
	turrel.cpp
	watchtower.cpp
	zombie.cpp
)

target_link_libraries(bt_objects PRIVATE btanks_engine sdlx mrt expat::expat SDL::SDL)
