find_path(DIRECTXSDK_INCLUDE_DIR d3d9.h PATH_SUFFIXES directxsdk)

find_library(DIRECTXSDK_D3D9_LIB d3d9.lib)
add_library(DirectXSDK::D3D9 UNKNOWN IMPORTED)
set_target_properties(DirectXSDK::D3D9 PROPERTIES
	IMPORTED_LINK_INTERFACE_LANGUAGES "C"
	INTERFACE_INCLUDE_DIRECTORIES "${DIRECTXSDK_INCLUDE_DIR}"
	IMPORTED_LOCATION "${DIRECTXSDK_D3D9_LIB}")

find_library(DIRECTXSDK_D3DX9_LIB d3dx9.lib)
add_library(DirectXSDK::D3DX9 UNKNOWN IMPORTED)
set_target_properties(DirectXSDK::D3DX9 PROPERTIES
	IMPORTED_LINK_INTERFACE_LANGUAGES "C"
	INTERFACE_INCLUDE_DIRECTORIES "${DIRECTXSDK_INCLUDE_DIR}"
	IMPORTED_LOCATION "${DIRECTXSDK_D3DX9_LIB}")
